[features]
seeds = false

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = [
  "wen_migration",
]

[programs.localnet]
wen_migration = "wns1gDLt8fgLcGhWi5MqAqgXpwEP1JftKE9eZnXS1HM"

[scripts]
test = "cd ../client && yarn test"


[test.validator]
url = "https://api.mainnet-beta.solana.com"

[[test.validator.clone]]
address = "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"
